void putstring(char *s) {
  while (*s) {
    putchar(*s);
    s = s + 1;
  }
}

void putnumber(int n) {
  int i = 0;
  int digits[10];
  if (n == 0) {
    putchar('0');
    return;
  }
  if (n < 0) {
    putchar('-');
    n = -n;
  }
  while (n > 0) {
    digits[i] = n % 10;
    n = n / 10;
    i = i + 1;
  }
  i = i - 1;
  while (i >= 0) {
    putchar(digits[i] + '0');
    i = i - 1;
  }
}

int main() {
  int x;
  int y;
  int z;

  x = 42;
  y = 128;

  z = ++x;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = --x;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x++;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x--;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x += y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x -= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);  
  z = x *= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x /= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x %= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x &= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x |= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x ^= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x <<= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = x >>= y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = ~z;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = +z;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = 1 ? x : y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);
  z = 0 ? x : y;
  putstring("x: ");
  putnumber(x);
  putchar(',');
  putchar(' ');
  putstring("y: ");
  putnumber(y);
  putchar(',');
  putchar(' ');
  putstring("z: ");
  putnumber(z);
  putchar(10);

  return 0;
}
