#! /bin/sh
#
# Bootstrap pnut-exe from C4: C in four functions.
#
# This script bootstraps pnut-exe from C4, a minimal self-contained C compiler
# that compiles C to bytecode and executes it.
# C4 doesn't support have a preprocessor, so we preprocess pnut's source code
# with cpp.c, a C4 compatible preprocessor, into pnut-exe.c. pnut-exe.c is then
# executed by C4 and used to compile pnut-exe.

set -eux

BUILD_OPT_EXE_Linux_i386="-Dtarget_i386_linux -DONE_PASS_GENERATOR"
BUILD_OPT_EXE_Linux_x86_64="-Dtarget_x86_64_linux -DONE_PASS_GENERATOR"
BUILD_OPT_EXE_Darwin_x86_64="-Dtarget_x86_64_mac"
BUILD_OPT_EXE_Darwin_arm64="-Dtarget_x86_64_mac" # no arm64 backend yet, x86 is emulated on ARM Macs

# Handle custom target selection

  # Detect the operating system and architecture
os=$(uname -s)
arch=$(uname -m)
target="${os}_${arch}"

BUILD_OPT_EXE=$(eval echo \$BUILD_OPT_EXE_${target})

TEMP_DIR="build"
mkdir -p "$TEMP_DIR"

CLONE_DIR="$TEMP_DIR/bootstrap-C4"
C4_DIR="$CLONE_DIR/c4-pnut"

if [ -e "$CLONE_DIR" ]; then
  echo "C4 directory already exists, skipping clone"
else
  git clone https://github.com/laurenthuberdeau/bootstrap-C4.git $CLONE_DIR
  TOP=$(pwd)
  cd $CLONE_DIR && git checkout laurent/c4-for-pnut-exe-bootstrap && cd $TOP
fi

PNUT_EXE_OPTS="$BUILD_OPT_EXE -DPNUT_BOOTSTRAP"
C4_COMPAT="-DPNUT_CC -DNO_CONST_SUPPORT -DPUTCHAR_WITH_PRINTF -DNO_SUPPORT_TENTATIVE_DECLS -DDISABLE_INTEGER_OVERFLOW_CHECK"

gcc "$C4_DIR/c4.c" -o "$TEMP_DIR/c4"
./$TEMP_DIR/c4 "$C4_DIR/cpp.c" pnut.c $PNUT_EXE_OPTS $C4_COMPAT > $TEMP_DIR/pnut-exe.c
./$TEMP_DIR/c4 $TEMP_DIR/pnut-exe.c pnut.c $PNUT_EXE_OPTS -o "$TEMP_DIR/pnut-exe-by-c4"

make bootstrap-pnut-exe TARGET="$os.$arch" MINIMAL=1
if diff -q $TEMP_DIR/pnut-exe-by-c4 build/pnut-exe-bootstrapped; then
  echo "✅ Bootstrapped pnut-exe matches the one generated by c4"
else
  echo "❌ Bootstrapped pnut-exe does not match the one generated by c4"
  sha256sum pnut-exe-by-c4 build/pnut-exe-bootstrapped
  exit 1
fi
