#!/bin/sh

PATH=/usr/local/Gambit/bin:$PATH

source_file="$1"
output_file="${source_file%.*}.sh"
temp_file="${source_file%.*}.temp"

echo "*** compiling $source_file -> $output_file"

gcc -E -C -P -DSIX_CC "$source_file" > "$temp_file"

./six-cc.scm "$temp_file" > "$output_file"

chmod +x "$output_file"

for shell in "ksh" "zsh " "dash" "bash" ; do
    echo "`/usr/bin/time $shell "$output_file" < big.c 2>&1 | sed -e 's/ real.*//'` $shell"
done

rm "$temp_file"
