//########################### C to shell translation ###########################
//
// This comment block describes how this shell script was generated from C
// source code, the mapping of the C language to shell, and how to review it.
//
// This script was generated from C source code using the pnut-sh transpiler,
// which is part of the pnut project. Pnut-sh has an option to include the
// original C source code as comments in the generated shell script, which is
// what you see here. The C source code is included verbatim, with no
// modifications, and is interleaved with the generated shell code.
//
#ifdef target_sh
// This script can extract the original C source code from itself using the
// `-C <filename>` option, which outputs C code that can be used to regenerate
// exactly this script:
//    sh pnut-sh.sh -C pnut-sh.sh > pnut.c
//    sh pnut-sh.sh pnut.c > pnut-sh-again.sh
//    diff pnut-sh.sh pnut-sh-again.sh # the files are identical
#endif
#if defined(target_i386_linux) || defined (target_x86_64_linux) || defined (target_x86_64_mac)
// This script can extract the original C source code from itself using the
// `-C <filename>` option, which outputs C code that can be used to
// bootstrap an executable version of pnut-exe:
//    sh pnut-exe.sh -C pnut-exe.sh > pnut.c
//    sh pnut-exe.sh pnut.c > pnut-exe-from-annotations
//    # Fixed point test: can pnut-exe-from-annotations regenerate itself?
//    chmod +x pnut-exe-from-annotations
//    ./pnut-exe-from-annotations pnut.c > pnut-exe-from-annotations-again
//    diff pnut-exe-from-annotations pnut-exe-from-annotations-again
#endif
//
// The code generated by pnut-sh is designed to be readable and auditable, and
// thus the mapping from C to shell is as direct as possible. As such, the code
// should be easy to read and understand for anyone familiar with C, and the
// mapping evident in the structure of the code, the naming of variables and
// functions. In favor of brevity, this document does not explain the C syntax
// itself, but rather focuses on the differences and subtleties of the mapping
// from C to shell. These are:
//
// - The naming convention for variables and functions (name mangling).
// - How the C heap is implemented without array support, and arithmetic.
// - How functions (local variables, parameters, return values) are implemented.
// - Character and string literals.
//
// Importantly, this is done without dynamic code evaluation (`eval` command)
// that would make the code more difficult to read and audit.
//
// Features that don't have a direct mapping to shell (goto, switch
// fall-through, floating point numbers), or that are not used in pnut's source
// code, are not covered in this document.
// Refer to https://doi.org/10.1145/3687997.3695639 for more details.
//
//-------------------------------- Name mangling -------------------------------
//
// POSIX shell variables and functions all share the same namespace, and thus a
// naming convention is used to avoid collisions between variables and
// functions, and with internal variables and functions used by the generated
// shell code. The convention is as follows:
// - Local variables are named as-is, with no mangling.
// - Global variables are prefixed with `_` to avoid collisions with local
//   variables.
// - Internal variables used by the generated shell code are prefixed with `__`
//   to avoid collisions with user-defined variables.
// - Functions are prefixed with `_` to avoid collisions with internal
//   functions, which are named without the underscore prefix.
//
// Because underscore (`_`) is used to avoid collisions between variables, C
// variables with leading underscores are not allowed.
//
//---------------------------- C Heap and arithmetic ---------------------------
//
// A heap is usually implemented using an array of bytes, but since POSIX shell
// doesn't offer an array data-structure, arrays are simulated using shell
// variables. Specifically, `_{address}` is used to store the value at a memory
// address, and arithmetic expansions can be used to dynamically refer to memory
// locations. For example, the C expression `*(p + 1)` is translated to
// `_$((p + 1))`. Arithmetic expansions can also be nested, and are expanded
// inside-out, with `arr[i] = 42;` mapping to `: $((_$((arr + i)) = 42))`.
// Notice the `:` builtin command, used to ignore the output of the assignment.
//
// `malloc` and `free` are implemented on top of this heap, and the memory
// management, using a simple bump allocator, is handled by the runtime
// functions.
//
//---------------------------------- Functions ---------------------------------
//
// Shell functions are more like procedures in that they don't have a return
// value (other than exit code), and do not have local variables. Additionally,
// their parameters are passed as positional parameters (`$1`, `$2`, ...), and
// not as named variables.
//
// In general, shell functions can return values by assigning to global
// variables, which can then be read by the caller of the function. Because
// arithmetic expansion can assign to variables dynamically, functions take as
// their first argument the name of the variable that receives the result (the
// "return variable"). Returning a value from a function is then done by
// assigning to this return variable like so: `: $(($1 = result))`. When
// ignoring the result of a function, the `__` return variable is used by
// convention.
//
// We use the term local variable to refer to a programmer-declared local
// variable or parameter, or a compiler-introduced temporary. Since POSIX shell
// offers only globally scoped variables, local scoping of variables is achieved
// with a shallow binding approach. For this, we use a callee-save calling
// convention. Every function begins by saving its local variables to a stack so
// that the function is free to clobber them. The variables are then restored to
// their original values when the function returns. Unlike the traditional C
// stack implementation, this stack is used solely for saving local variable
// values, and is not used for control flow, meaning no stack space is used by
// functions with no local variables. To keep the bookkeeping of local variables
// out of the way, it is abstracted using the `let` and `endlet` runtime
// functions.
//
//------------------------ Character and string literals -----------------------
//
// POSIX shell does not have character literals like C, where character literals
// are represented as integers corresponding to the character's ASCII code.
// To avoid the use of such ASCII codes directly in the shell code, which would
// be difficult to read, character literals are replaced by readonly variables
// initialized to the character's ASCII code, named after the character. For
// example, 'a' is replaced with `__a__`, which is initialized to 97.
// Non-alphanumeric characters are replaced with descriptive names, for example
// ' ' is replaced with `__space__`.
//
// In shell, string values can be modified only using the provided interface.
// This interface is limited, being primarily useful for concatenating, cutting,
// and comparing strings, and it does not allow random access to characters --
// one of the most common access patterns used in C programs. As a result, shell
// strings must be unpacked into arrays of characters before they can be used.
// This is done by the `defstr` function, which takes a string literal and a
// variable name, and initializes the variable to point to the unpacked string.
// For example, `putchar("0123456789abcdef"[n & 15])` maps to:
//    defstr __str_0 "0123456789abcdef"
//    putchar __ $((__str_0 + (n & 15)))
//